# Generated by Django 4.2.1 on 2023-05-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "original_url",
                    models.URLField(max_length=2048, primary_key=True, serialize=False),
                ),
                ("short_url", models.CharField(max_length=8, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
