# Generated by Django 4.2.1 on 2023-05-12 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="last_access",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 5, 12, 0, 0)
            ),
        ),
    ]
